### ISSUE TITLE
Detected blocking call to sleep inside the event loop...

### ISSUE THREAD

**Issue by Johndolk** [J-Lindvig/Fuelprices_DK#11]
Hej Jakob

For denne fejl i loggen:

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for fuelprices_dk doing blocking calls at custom_components/fuelprices_dk/sensor.py, line 36: time.sleep(3)

**Comment by J-Lindvig** [comment]
Tak.Der var nogle issues hvor integrationen mistede forbindelsen med de forskellige sider. Denne sleep var et af værktøjerne til at "holde" forbindelsen.Jeg vil prøve at fjerne den igen ./Jacob 18. nov. 2022 11.04 skrev Johndolk ***@***.***>:
Hej Jakob
For denne fejl i loggen:
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for fuelprices_dk doing blocking calls at custom_components/fuelprices_dk/sensor.py, line 36: time.sleep(3)

**Comment by rbjoensen** [comment]
Hej Er der noget nyt i ovenstående?

**Comment by J-Lindvig** [comment]
> Hej Er der noget nyt i ovenstående?

Fra version 1.4 skulle der være styr på de omtalte time-outs
![image](https://user-images.githubusercontent.com/54498188/208313140-57fcec02-8358-48f6-9612-03868adc4f41.png)
Såfremt dette ikke er tilfældet hos dig, så åbn gerne et nyt issue.

/Jacob
