### ISSUE TITLE
Detected blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by TripelJ** [J-Lindvig/Fuelprices_DK#12]
Hi There, 

Thanks for the integration. :) 

Wanted to let you know with the new release of HA 2022.12 I noticed in the logs that the integrations complains and it tells me to inform you about it. 

`Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for fuelprices_dk doing blocking calls at custom_components/fuelprices_dk/sensor.py, line 36: time.sleep(3)`

now it's reported :)

Best regards.

**Comment by J-Lindvig** [comment]
Thank you, I will try to find another method./Jacob 21. dec. 2022 10.05 skrev TripelJ ***@***.***>:
Hi There,
Thanks for the integration. :)
Wanted to let you know with the new release of HA 2022.12 I noticed in the logs that the integrations complains and it tells me to inform you about it.
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for fuelprices_dk doing blocking calls at custom_components/fuelprices_dk/sensor.py, line 36: time.sleep(3)
now it's reported :)
Best regards.

**Comment by mm98** [comment]
Hi,

I have made some tests over the last two weeks. Removed the blocking calls and switched to `asyncio`, which supports non-blocking `await asyncio.sleep(3)`. 

Pull request https://github.com/J-Lindvig/Fuelprices_DK/pull/13

**Comment by J-Lindvig** [comment]
Great, thnak you sp much for your contribution.
Changing the code as we "speak" - update will follow soon.

**Comment by J-Lindvig** [comment]
Added the new timeout.
And fixed a new error since Circle K had changed it site + added charger from Circle K.
