### ISSUE TITLE
filter out values

### ISSUE THREAD

**Issue by rhgiter** [J-Lindvig/Fuelprices_DK#2]
how do I filter out values ? 
I get all values i HA 

my code :

fuelprices_dk:
  # Optional entries
  companies:
  # possible values are: circlek, f24, goon, ingo, oil, ok, q8 and shell
    - ingo
    - shell
  fueltypes:
  # Possible values are: oktan 95, oktan 95+, oktan 100, diesel, diesel+
    - oktan 95
    - oktan 95+

**Comment by J-Lindvig** [comment]
...wait saw a glitch.... Will investigate further.....

**Comment by J-Lindvig** [comment]
Thank you for reporting the issue.

There was a mismatch in the const.py which contains the keywords used in the config.

It have now been fixed.

/Jacob
