### ISSUE TITLE
Cirkle K

### ISSUE THREAD

**Issue by BrianKnudsen** [J-Lindvig/Fuelprices_DK#20]
Jeg får ingen pris på Cirkle K oktan 95  der står bare utilgængelig. men der er ikke problmer med de andre selskaber

**Comment by pawjensen** [comment]
see comments at #18

**Comment by ijensen79** [comment]
Jeg har prøvet at rette lidt i koden og min henter priser nu. de havde rettet navnene hvad den skulle hente  
        "name": "Circle K",
        "url": "https://www.circlek.dk/priser",
        "products": {
            OCTANE_95: {"name": "miles95."},
            OCTANE_95_PLUS: {"name": "miles+95."},
            DIESEL: {"name": "miles Diesel."},
            DIESEL_PLUS: {"name": "milesPLUS Diesel"},
            ELECTRIC: {"name": "El Lynlader."},
