### ISSUE TITLE
Numeric values

### ISSUE THREAD

**Issue by ksga** [J-Lindvig/Fuelprices_DK#3]
Great plugin - now I'll know in advance that prices are on the rise once again :)

It seems the values are interpreted as strings, not numbers:
![billede](https://user-images.githubusercontent.com/546026/174543417-81e1f3ac-63dd-465b-845a-1d2e4daa0455.png)

It looks the same as for example a pressure sensor - but does not act the same...
![billede](https://user-images.githubusercontent.com/546026/174543572-5083af6c-8d14-4e68-9cca-67376bf05cf2.png)

Maybe adding a "unit_of_measurement" would solve it? Or is the issue related to the "[object Object][object Object][object Object]" shown on the card?

**Comment by J-Lindvig** [comment]
Thank you for your kind words.

I Will look into the matter when possible.

What I find odd in your screenshots is tha on your "working" sensor you have "," as decimal point and not ".".

I will try to add a unit of measurement or some other trials.

/Jacob

**Comment by J-Lindvig** [comment]
Found it....

![image](https://user-images.githubusercontent.com/54498188/174602559-b765341d-677f-473a-ae00-4277e2c78809.png)

Will make a permanent fix later and upload.

Thanks for reporting.
