### ISSUE TITLE
henter ikke priser siden d 10 august

### ISSUE THREAD

**Issue by ghozt1989** [J-Lindvig/Fuelprices_DK#6]
Hej Jacob.

Først tak for dit store arbejde som kan hjælpe alle os andre. 

Jeg ved ikke om det er mit system den er gal med eller hvad der sker for jeg kan se mit ha ikke har kunne hente rigtig pris den sidste lille uge sidst den kom med rigig pris var d 10 august 

![image](https://user-images.githubusercontent.com/7705364/185058085-38b05d02-0b5e-4dd4-a475-b25c13b9f112.png)
![image](https://user-images.githubusercontent.com/7705364/185058143-7be5d843-5f00-481f-b606-30e6d10a4aad.png)

**Comment by maxandersen** [comment]
maaske relateret til https://github.com/J-Lindvig/Fuelprices_DK/issues/5 ?

**Comment by ghozt1989** [comment]
> maaske relateret til #5 ?

Måske. Syntes bare det mystisk min først er begyndt på det d 10 august og din for 22 dage siden. Derfor kædet jeg dem ikke sammen :)

**Comment by J-Lindvig** [comment]
Jeg har ikke glemt jer eller arbejdet med de udfordringer som I møder ved Fuelprices. Lige pt. er jeg dog lidt presset på tid grundet mit primære job og aktiviteter i hjemmet.

Fuelprices bruger webscraping og ved en ændring i et selskabs webside kan der opstå fejl eller huller i data.

Jeg har planer om en bedre logging af scarpingen, så der bliver nemt at finde ud af hvorfor det ikke virker.

MVH Jacob

**Comment by ghozt1989** [comment]
> Jeg har ikke glemt jer eller arbejdet med de udfordringer som I møder ved Fuelprices. Lige pt. er jeg dog lidt presset på tid grundet mit primære job og aktiviteter i hjemmet.
> 
> Fuelprices bruger webscraping og ved en ændring i et selskabs webside kan der opstå fejl eller huller i data.
> 
> Jeg har planer om en bedre logging af scarpingen, så der bliver nemt at finde ud af hvorfor det ikke virker.
> 
> MVH Jacob

Det helt fint. Jeg sætter stor pris på dit arbejde med både dette projekt og mange af dine andre projekter. Jeg afventer spændt. 

Rigtig go dag :)

**Comment by J-Lindvig** [comment]
Prøv med den nyeste version(1.3.1)

**Comment by ghozt1989** [comment]
> Prøv med den nyeste version(1.3.1)

Sådan lige umildbart ser det ikke ud til at have virket. Men jeg lader lige min HA genstarte helt nu også ser jeg i morgen om den virker nu :)

**Comment by ghozt1989** [comment]
> Prøv med den nyeste version(1.3.1)

Virker desværre stadig ikke den har stadig udfald og påstår prisen er 16.09 :(

**Comment by J-Lindvig** [comment]
Er det alle selskaber som du oplever dette ved?

**Comment by ghozt1989** [comment]
> Er det alle selskaber som du oplever dette ved?

Ja :(
