### ISSUE TITLE
Virker denne integration

### ISSUE THREAD

**Issue by kurtSejr** [J-Lindvig/Fuelprices_DK#7]
Denne integration ser ikke ud til at virke, måske der er et behov for yderligere detaljer vedr. installation - fx. hvor skal Config data skrives?

**Comment by kurtSejr** [comment]
Har fundet denne fejlmelding under logs

Setup of sensor platform fuelprices_dk is taking over 10 seconds.

**Comment by J-Lindvig** [comment]
Ja, de

> Har fundet denne fejlmelding under logs
> 
> Setup of sensor platform fuelprices_dk is taking over 10 seconds.

Det er meget normalt, specielt hvis du ønsker alle priser fra alle selskaber, da integrationen skal hente mindst en webside for hvert selskab og trække data ud for hvert produkt.

**Comment by kurtSejr** [comment]
**Virker nu**, en af udfordringerne er at den ikke bliver synlig under integrationer, så udfordringen er nok mest en tydeligere dokumentation. 
Prisen på Shell blyfri er forkert, F24 er rigtig.

**Comment by J-Lindvig** [comment]
Jeg er altid åben for forbedringer af integrationen såvel som dokumentationen.

Omkring Shell Blyfri. så ser jeg ikke samme fejl her.
![image](https://user-images.githubusercontent.com/54498188/189480700-fe783e44-97f9-4143-a1c9-89d5e037b257.png)
![image](https://user-images.githubusercontent.com/54498188/189480708-7b0745fc-6ee1-4bf2-8311-372940c7c2a3.png)
