### ISSUE TITLE
Connecting problems

### ISSUE THREAD

**Issue by Rocologo** [J-Lindvig/Fuelprices_DK#8]
Jeg får denne fejl når HA starter.

This error originated from a custom integration.

Logger: custom_components.fuelprices_dk.sensor
Source: helpers/update_coordinator.py:151
Integration: Fuelprices DK (documentation, issues)
First occurred: September 25, 2022 at 10:57:47 (17 occurrences)
Last logged: 19:58:51

Error requesting sensor data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by Rocologo** [comment]
Efter jeg opgradede ha lige nu og genstartede så får jeg igen priserne ind i ha.... Mærkeligt...

**Comment by J-Lindvig** [comment]
Version 1.4 har fået indbygget nogle flere "tricks" til at holde forbindelsen.
