### ISSUE TITLE
Sensor seems to go offline every 2 hours or so

### ISSUE THREAD

**Issue by Icarus81** [J-Lindvig/Fuelprices_DK#9]
The sensor seems to be on/off in periods. Making the otherwise great integration semi useless.

![Skærmbillede 2022-10-30 215037](https://user-images.githubusercontent.com/66039829/198900866-f197ee4a-8453-49ce-9582-de7f75832314.jpg)

**Comment by J-Lindvig** [comment]
Strange behavior....

In my setup with only OK, I haven't seen these issues.

I will try to add F24 myself and see if I can spot any errors.

Thanks for reporting.

/Jacob

**Comment by Icarus81** [comment]
Hi Jacob. I have the same issue with all other sensors including OK. 
![11FC1184-74D7-42F2-A7A1-C5D722A9C6CC](https://user-images.githubusercontent.com/66039829/198962330-aa060e7d-5759-470c-b20b-266f799aa4dd.png)

**Comment by J-Lindvig** [comment]
Fixed with v1.4
